name: Update Fund NAV Daily

on:
  schedule:
    # 每天北京时间18点运行（UTC时间10点）
    - cron: '0 10 * * *'
  workflow_dispatch:  # 允许手动触发

jobs:
  update-nav:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Update NAV values
      run: |
        python excel_nav_updater.py
        
    - name: Commit and push if changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add Asset.xlsx
        git diff --quiet && git diff --staged --quiet || git commit -m "Auto-update NAV values [skip ci]"
        git push
