name: Update Fund NAV Daily

on:
  schedule:
    - cron: '0 10 * * *'  # 每天UTC 10:00 (北京时间18:00)
  workflow_dispatch:

jobs:
  update-nav:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
        
    - name: Install dependencies
      run: |
        pip install pandas openpyxl requests
        
    - name: Run NAV updater
      run: python excel_nav_updater.py
      
    - name: Commit changes
      run: |
        git config --local user.name "github-actions[bot]"
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git add Asset.xlsx
        git diff --cached --quiet || git commit -m "Auto-update NAV values"
        git push
